### ISSUE TITLE
load.sh fails build with Error 2

### ISSUE THREAD

**Issue by theweefies** [vanhoefm/ath_masker#4]
root@kali:~/ath_masker# ./load.sh 
make -C /lib/modules/5.16.0-kali1-amd64/build  M=/root/ath_masker
make[1]: Entering directory '/usr/src/linux-headers-5.16.0-kali1-amd64'
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali1-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali1-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali1-common/scripts/pahole-flags.sh: not found
  CC [M]  /root/ath_masker/ath_masker.o
/root/ath_masker/ath_masker.c: In function ‘kprobe_init’:
/root/ath_masker/ath_masker.c:97:12: error: ‘struct kprobe’ has no member named ‘fault_handler’; did you mean ‘post_handler’?
   97 |         kp.fault_handler = handler_fault;
      |            ^~~~~~~~~~~~~
      |            post_handler
make[2]: *** [/usr/src/linux-headers-5.16.0-kali1-common/scripts/Makefile.build:292: /root/ath_masker/ath_masker.o] Error 1
make[1]: *** [/usr/src/linux-headers-5.16.0-kali1-common/Makefile:1870: /root/ath_masker] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.16.0-kali1-amd64'
make: *** [Makefile:5: all] Error 2

**Comment by byroncorrea57** [comment]
> root@kali:~/ath_masker# ./load.sh make -C /lib/modules/5.16.0-kali1-amd64/build M=/root/ath_masker make[1]: Entering directory '/usr/src/linux-headers-5.16.0-kali1-amd64' /bin/sh: 1: /usr/src/linux-headers-5.16.0-kali1-common/scripts/pahole-flags.sh: not found /bin/sh: 1: /usr/src/linux-headers-5.16.0-kali1-common/scripts/pahole-flags.sh: not found /bin/sh: 1: /usr/src/linux-headers-5.16.0-kali1-common/scripts/pahole-flags.sh: not found CC [M] /root/ath_masker/ath_masker.o /root/ath_masker/ath_masker.c: In function ‘kprobe_init’: /root/ath_masker/ath_masker.c:97:12: error: ‘struct kprobe’ has no member named ‘fault_handler’; did you mean ‘post_handler’? 97 | kp.fault_handler = handler_fault; | ^~~~~~~~~~~~~ | post_handler make[2]: *** [/usr/src/linux-headers-5.16.0-kali1-common/scripts/Makefile.build:292: /root/ath_masker/ath_masker.o] Error 1 make[1]: *** [/usr/src/linux-headers-5.16.0-kali1-common/Makefile:1870: /root/ath_masker] Error 2 make[1]: Leaving directory '/usr/src/linux-headers-5.16.0-kali1-amd64' make: *** [Makefile:5: all] Error 2

**Comment by koilbord** [comment]
do you found a solution for this error?

**Comment by vanhoefm** [comment]
This should be fixed now.
