### ISSUE TITLE
load.sh failed

### ISSUE THREAD

**Issue by koilbord** [vanhoefm/ath_masker#5]
I get this error, need some help:

make -C /lib/modules/4.19.118-Re4son-v8+/build  M=/root/ath_masker
make[1]: Entering directory '/usr/src/linux-headers-4.19.118-Re4son-v8+'
  CC [M]  /root/ath_masker/ath_masker.o
/root/ath_masker/ath_masker.c: In function 'handler_pre':
/root/ath_masker/ath_masker.c:55:63: error: 'common' undeclared (first use in this function); did you mean 'ns_common'?
   55 | printk("pre_handler: MAC address of device is %pM\n", common->macaddr);
      |                                                       ^~~~~~
      |                                                       ns_common
/root/ath_masker/ath_masker.c:55:63: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:310: /root/ath_masker/ath_masker.o] Error 1
make[1]: *** [Makefile:1522: _module_/root/ath_masker] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.118-Re4son-v8+'
make: *** [Makefile:5: all] Error 2

**Comment by vanhoefm** [comment]
Looks like you were compiling the module for a CPU that wasn't supported. With the recent merge that adds support for ARM64 this may be fixed now.

**Comment by koilbord** [comment]
thanks!! this issue can be closed
